obj-$(CONFIG_RP_POWER)		+= rp_power.o
obj-$(CONFIG_RP_GPIO)				+= rp_gpio.o
obj-$(CONFIG_RP_STM706)      	+= stm706.o
obj-$(CONFIG_RP_FAN)           += rp_fan_power.o
obj-$(CONFIG_RP_KEY) += rp_keys.o
